- hosts: devstack_instances
  tasks:

  - name: get the cinder commit sha
    sudo: no
    shell: echo cinder_commit_id `git rev-parse --short HEAD` > /opt/stack/tempest/console.log.out
    args:
      chdir: /opt/stack/cinder
    ignore_errors: True

  - name: run tempest nfs
    sudo: no
    shell: tox -eall -- '(?!.*(volume_upload|volume_backup))volume' | tee -a console.log.out
    args:
      chdir: /opt/stack/tempest

  - name: Fetch tempest log
    sudo: yes
    fetch: src=/opt/stack/tempest/console.log.out dest={{ results_dir }}/console.log.out flat=yes validate_md5=no

  - name: Fetch tempest log
    sudo: yes
    fetch: src=/opt/stack/tempest/console.log.out dest=/tmp/{{ instance_name }}.console.log.out flat=yes validate_md5=no
